server:
  port: 8888
spring:
  #json 时间转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:sqlserver://192.168.200.241:1433;DatabaseName=web_wechat
      username: sa
      password: 123qwe,.
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      initial-size: 3
      min-idle: 5
      max-active: 20
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/lannis/mybatisplus/**/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
logging:
  level:
    com.lannis.mybatisplus.mapper: debug
